[messages.fire_sound.fields]
source = { type = "EntityId" }

# this is to receive the walk trigger source from other server
[messages.foot_on_ground.fields]
source = { type = "EntityId" }

# send from audio server to audio client
[messages.walk_sound.fields]
source = { type = "EntityId" }

# send from audio server to audio client
[messages.explosion.fields]
pos = { type = "Vec3" }
