[ember]
id = "afps"
name = "afps"
version = "0.0.1"

includes = [
    "src/zombie/ambient.toml",
    "src/fpsmodel/ambient.toml",
    "src/fpsmovement/ambient.toml",
    "src/fpsrule/ambient.toml",
    "src/fpsanim/ambient.toml",
    "src/fpsui/ambient.toml",
    "src/fpsaudio/ambient.toml",
    "src/droq_laserbox/ambient.toml",
    "src/console/ambient.toml",
    "src/droq_laserbox/ambient.toml",
]