[package]
name = "afps"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
# ambient_api = { path = "../Ambient/guest/rust/api" }
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", rev = "10c57e36c7da588195ec526acb9ef96ee27e0dcb" }
rhai = { version = "1.15", features = ["sync"] }
regex = "1"
glam = "0.24.1"

# Group 1: show the UI
# This include the aiming cross in the middle of the screen
# Use TAB key to toggle the scoreboard
# The "Rule" mod provides the calculation for player's score/health, etc.
# It's also the foundation of the future animation mod
# When the player health changes, "Hit" or "Death" animation will be triggered

[[bin]]
name = "fpsui_client"
path = "src/fpsui/client.rs"
required-features = ["client"]

[[bin]]
name = "fpsui_server"
path = "src/fpsui/server.rs"
required-features = ["server"]

[[bin]]
name = "fpsrule_server"
path = "src/fpsrule/server.rs"
required-features = ["server"]

# Group 2: show the scene
# For now, I only put a demo quad there, you can edit this as the game scene

[[bin]]
name = "scene_server"
path = "src/scene/server.rs"
required-features = ["server"]

# # Group 3: show the players' model
# # This will show a T-pose player and you cannot move

[[bin]]
name = "fpsmodel_client"
path = "src/fpsmodel/client.rs"
required-features = ["client"]

[[bin]]
name = "fpsmodel_server"
path = "src/fpsmodel/server.rs"
required-features = ["server"]

# # Group 4: add the movement system
# # Now you can move your model with mouse/keyboard

[[bin]]
name = "fpsmovement_client"
path = "src/fpsmovement/client.rs"
required-features = ["client"]

[[bin]]
name = "fpsmovement_server"
path = "src/fpsmovement/server.rs"
required-features = ["server"]

# # Group 5: Animation

[[bin]]
name = "fpsanim_server"
path = "src/fpsanim/server.rs"
required-features = ["server"]

# # Group 6: The audio system

[[bin]]
name = "fpsaudio_client"
path = "src/fpsaudio/client.rs"
required-features = ["client"]

[[bin]]
name = "fpsaudio_server"
path = "src/fpsaudio/server.rs"
required-features = ["server"]

# Group 7: Optional and unfinished Zombie system
# The Zombie rules and health/hit anim is not included yet
# They simply spawan and chase the nearest player

[[bin]]
name = "zombie_server"
path = "src/zombie/server.rs"
required-features = ["server"]

[[bin]]
name = "zombie_client"
path = "src/zombie/client.rs"
required-features = ["client"]

# Group 8: Laserbox.
# A laser that can be toggled by shooting the box
# that is its source

[[bin]]
name = "droq_laserbox_server"
path = "src/droq_laserbox/server.rs"
required-features = ["server"]

[[bin]]
name = "droq_laserbox_client"
path = "src/droq_laserbox/client.rs"
required-features = ["client"]

[[bin]]
name = "droq_laserbox_placement1_server"
path = "src/droq_laserbox_placement1/server.rs"
required-features = ["server"]

[[bin]]
name = "godot_sceneloader_server"
path = "src/godot_sceneloader/server.rs"
required-features = ["server"]

# ----------------------------------------------------------------
# The console is a temporary debugging utility that lives in-game.
# It should hopefully be moved to its own separate ember in the future.
[[bin]]
name = "console_client"
path = "src/console/client.rs"
required-features = ["client"]

[[bin]]
name = "console_server"
path = "src/console/server.rs"
required-features = ["server"]


[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]
