[components]

player_team = { type = "U8", description = "", attributes = [
    "Debuggable",
    "Networked",
] }


game_type = { type = "U8", description = "0: zombie mode", attributes = [
    "Debuggable",
    "Networked",
] }

player_killcount = { type = "I32", attributes = ["Debuggable", "Networked"] }

player_deathcount = { type = "I32", attributes = ["Debuggable", "Networked"] }

player_health = { type = "I32", attributes = ["Debuggable", "Networked"] }

hit_freeze = { type = "I32", attributes = ["Debuggable", "Networked"] }

heal_timeout = { type = "I32", attributes = ["Debuggable"] }

[messages.shoot.fields]
ray_origin = { type = "Vec3" }
ray_dir = { type = "Vec3" }
source = { type = "EntityId" }
# type_action = { type = "U8" }
