[components]

run = { type = { type = "Vec", element_type = "EntityId" }, attributes = [
    "Debuggable",
    "Networked",
] }

jump = { type = { type = "Vec", element_type = "EntityId" }, attributes = [
    "Debuggable",
    "Networked",
] }

hit = { type = { type = "Vec", element_type = "EntityId" }, attributes = [
    "Debuggable",
    "Networked",
] }

death = { type = { type = "Vec", element_type = "EntityId" }, attributes = [
    "Debuggable",
    "Networked",
] }

fire = { type = { type = "Vec", element_type = "EntityId" }, name = "fire", description = "fire", attributes = [
    "Debuggable",
    "Networked",
] }

fd_rt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
fd_lt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
bk_lt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
bk_rt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_fd = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_bk = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_lt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_rt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_fd_lt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_fd_rt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_bk_lt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
idle_bk_rt = { type = { type = "Vec", element_type = "EntityId" }, name = "fd_rt", description = "fd_rt", attributes = [
    "Debuggable",
    "Networked",
] }
