[[pipelines]]
type = "Models"
sources = ["Buildings/**/*"]

[[pipelines]]
type = "Models"
sources = ["Props/**/*"]

[[pipelines]]
type = "Models"
sources = ["model/**/*"]

[[pipelines]]
type = "Models"
sources = ["anim/**/*"]

[[pipelines]]
type = "Models"
sources = ["map/**/*"]

[pipelines.collider]
type = "FromModel"

[[pipelines]]
type = "Models"
sources = ["gun/**/*"]

[[pipelines]]
type = "Audio"
convert = true
sources = ["sound/**/*"]

[[pipelines]]
type = "Materials"
output_decals = false

[pipelines.importer]
type = "Single"
name = "afps"
base_color = "afps.jpeg"
