[components]

player_running = { type = "Bool", attributes = ["Debuggable", "Networked"] }

player_direction = { type = "Vec2", attributes = ["Debuggable", "Networked"] }

player_yaw = { type = "F32", name = "Player yaw", description = "The player's yaw.", attributes = [
    "Debuggable",
    "Networked",
] }

player_pitch = { type = "F32", name = "Player pitch", description = "The player's pitch.", attributes = [
    "Debuggable",
    "Networked",
] }

player_vspeed = { type = "F32", name = "Player vertical speed", description = "The player's vertical speed.", attributes = [
    "Debuggable",
    "Networked",
] }

player_shooting_status = { type = "Bool", description = "True when the player is in shooting", attributes = [
    "Debuggable",
    "Networked",
] }

player_zoomed = { type = "Bool", attributes = ["Debuggable"] }

[messages.input.fields]
direction = { type = "Vec2", description = "wasd state for movement direction; strafe;" }
mouse_delta = { type = "Vec2", description = "The mouse delta used for pitch and yaw" }
shoot = { type = "Bool", description = "Becomes true on the exact frame when the player pressed the shoot button" }
toggle_zoom = { type = "Bool", description = "Toggle scope/zoom" }
is_shooting = { type = "Bool", description = "Whether the player is in shooting or not; used for anim" }
ray_origin = { type = "Vec3", description = "The origin of the ray cast from the camera" }
ray_dir = { type = "Vec3", description = "The direction of the ray cast from the camera" }
duck = { type = "Bool", description = "Use CTRL to walk slow and quiet" }
jump = { type = "Bool" }
running = { type = "Bool" }

[messages.request_input]
fields = {}

[messages.release_input]
fields = {}
